# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-haridwar"
BBFILE_PATTERN_meta-haridwar = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-haridwar = "6"

LAYERDEPENDS_meta-haridwar = "core"
LAYERSERIES_COMPAT_meta-haridwar = "wrynose"
